namespace OrgBloom.Domain.Enums;

public enum State
{
    None,
    WaitingForSubmitApplication,
    WaitingForSelectLanguage,
    WaitingForSelectMainMenu,
    WaitingForEnterFirstName,
    WaitingForEnterLastName,
    WaitingForSelectProfession,
    WaitingForEnterPatronomyc,
    WaitingForEnterDateOfBirth,
    WaitingForEnterDegree,
    WaitingForEnterSector,
    WaitingForEnterInvestmentAmount,
    WaitingForEnterPhoneNumber,
    WaitingForEnterEmail,
    WaitingForResendApplication,
    WaitingForEnterLanguages,
    WaitingForEnterExperience,
    WaitingForEnterAddress,
    WaitingForEnterArea,
    WaitingForEnterExpectation,
    WaitingForEnterPurpose,
    WaitingForEnterAboutProject,
    WaitingForEnterHelpType,
    WaitingForEnterRequiredFunding,
    WaitingForAssetInvested,
}
