name: Pre-production

on:
  push:
    branches: [ "unidevs" ]

jobs:
  build-api:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/backend/EcoLink.WebApi/
    - name: Build
      run: dotnet build --configuration Release --output out --verbosity normal ./src/backend/EcoLink.WebApi/

      
  build-bot:
    name: Build frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/frontend/EcoLink.Bot/
    - name: Build
      run: dotnet build --configuration Release --output out --verbosity normal ./src/frontend/EcoLink.Bot/